version: "3.9"
services:
  rest-api-crud-example:
    build: .
    container_name: spring_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/shopust
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver

  mysql_db:
    image: mysql:8.0
    container_name: mysql_container_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=shopust
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: