server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:mysql://localhost:3306/shopUST?serverTimezone=UTC
    username: root
    password: CITLALLI123